### PR TITLE
bug-fixing: PostgreSQL failed to check if the server wasn't turn on the SSL

### LINKED ISSUE #285: Native Postgresql connection without ssl enabled
I've following manual on how to config native probe for postgresql (https://github.com/megaease/easeprobe/blob/main/docs/Manual.md#78-native-client-probe-configuration)

here's my code:

```
client:
  - name: Posgresql
    driver: postgres
    host: postgis:5432
    username: xxxxx
    password: xxxxx

  - name: Pgbouncer
    driver: postgres
    host: pgbouncer:5432
    username: xxxxxx
    password: xxxxxx
```

and here's report:
```
Posgresql Failure ❌
postgis:5432 - ⏱ 4ms
Error (client/postgres): pgdriver: SSL is not enabled on the server
> EaseProbe v2.0.0 @ c0d124fc3faa at 2023-02-10 10:49:53 UTC

Pgbouncer Failure ❌
pgbouncer:5432 - ⏱ 2ms
Error (client/postgres): pgdriver: SSL is not enabled on the server
> EaseProbe v2.0.0 @ c0d124fc3faa at 2023-02-10 10:49:54 UTC
```

i'm using docker deployment method

### PR DESCRIPTION
**Pull request by haoel**
close #285 

## How to Reproduce

disable the SSL in `prostgresql.conf` by commenting on the following configuration 
```
#ssl = on
 #ssl_ca_file = '/path/to/certs/ca.crt'
 #ssl_cert_file = '/path/to/certs/server.crt'
 #ssl_key_file = '/path/to/certs/server.key'
```

EaseProbe config.yaml

```yaml
client:
  - name: PostgreSQL Native Client (local)
    driver: "postgres"
    host: "localhost:5432"
    username: user
    password: password
```

## Fix

if TLS in the client is not configured,  we need to configure it with a nil

```diff
@@ -62,8 +62,9 @@ func New(opt conf.Options) (*PostgreSQL, error) {
                return nil, fmt.Errorf("TLS Config Error - %v", err)
        } else if tls != nil {
                tls.InsecureSkipVerify = true
-               clientOptions = append(clientOptions, pgdriver.WithTLSConfig(tls))
        }
+       // if the tls is nil which means `sslmode=disable`
+       clientOptions = append(clientOptions, pgdriver.WithTLSConfig(tls))
```

> **Note**
> The other code change just move the code from the `Probe()` to `ProbeWithPing()` and `ProbeWithDataChecking()`, no code logics changes.

### CODE REVIEW

**Review by jenggo — APPROVED** [review]

File: probe/client/postgres/postgres.go [hunk 1]
```diff
@@ -97,60 +98,75 @@ func (r *PostgreSQL) checkData() error {
...
-		// run a SQL to test
-		row, err := db.Query(`SELECT 1`)
+		// query the data
+		log.Debugf("[%s / %s / %s] - SQL - [%s]", r.ProbeKind, r.ProbeName, r.ProbeTag, sqlstr)
+		rows, err := db.Query(sqlstr)
 		if err != nil {
+			return false, fmt.Sprintf("Query error - [%s], %v", v, err)
+		}
+		if !rows.Next() {
+			rows.Close()
```
Comment (localvar) [inline probe/client/postgres/postgres.go:154]: need call `db.Close()` in error cases?

**Review by samanhappy — APPROVED** [review]

File: probe/client/postgres/postgres.go (hunk 1 above)
Comment (haoel) [reply probe/client/postgres/postgres.go:154]: nice catch!

Comment (haoel) [reply probe/client/postgres/postgres.go]: I put the code in for loop into function`verifyData()`, and use the `defer db.Close() and defer rows.Close()` inside. 

Please review it again

**Review by localvar — APPROVED** [review]
